# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'rwethereyet' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for rwethereyet

  pod 'SwiftyGif', '~> 4.0'
  pod 'SwiftLocation', '~> 3.1.0'
  pod 'SwiftOverlays', '~> 4.0.0'
  use_frameworks! 

  target 'rwethereyetTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'rwethereyetUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
